apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "clamav.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: clamd
      protocol: TCP
      port: 3310
      targetPort: 3310
