{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "clamav.serviceAccountName" . }}
  labels:
{{ include "clamav.labels" . | indent 4 }}
{{- end -}}
