---
clusterName: "opensearch-cluster"

securityConfig:
  data: {}
    # config.yml: |-
    # internal_users.yml: |-
    # roles.yml: |-
    # roles_mapping.yml: |-
    # action_groups.yml: |-
    # tenants.yml: |-

tls:
  enabled: false
  issuer: {}

# Used for autocreating ism policy and index-template
indexName: filebeat

ism:
  rollover:
    period: 20h
  delete:
    period: 30d

metrics:
  serviceMonitor:
    enabled: false
    namespace: default
    # Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
    # ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
    additionalLabels: {}
    endpoints:
      - port: "http"
        path: /_prometheus/metrics
        scheme: https
        
  userSecrets: []
