{{- if .Values.originIssuer.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-issuer-{{ include "cloudflare_collection.fullname" . }}
type: Opaque
data:
{{- range $path, $bytes := .Values.originIssuer.secret }}
  {{ $path }}: '{{ $bytes | b64enc }}'
{{- end }}
{{- end }}
{{- if .Values.cloudflareOperator.enabled }}
{{- range $i, $zone := .Values.cloudflareOperator.accounts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-cloudflare-operator-{{ $zone.zone }}
type: Opaque
stringData:
  apiToken: {{ $zone.secret }}
{{- end }}
{{- end }}
