{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "auditbeat.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "auditbeat.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "auditbeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "auditbeat.fullname" . }}-kubeadm-config
subjects:
  - kind: ServiceAccount
    name: {{ template "auditbeat.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "auditbeat.fullname" . }}-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
{{- end }}
