{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "auditbeat.serviceAccountName" . }}
  labels:
{{ include "auditbeat.labels" . | indent 4 }}
{{- end -}}
