{{- range .Values.userSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-{{ $.Values.clusterName }}-user-{{ .username }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "opendistro.labels" $ | nindent 4 }}
type: Opaque
data:
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}
{{- end }}

{{- range .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-{{ $.Values.clusterName }}-extra-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "opendistro.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $item, $value := .data }}
  {{ $item }}: {{ $value | b64enc }}
{{- end }}
{{- end }}