{{- if .Values.securityConfig.config.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-{{ .Values.clusterName }}-securityconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opendistro.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.securityConfig.config.data }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
{{- end }}
{{- end }}
