apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-operator-kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - create
      - delete
      - get
      - patch
      - update
      - list
      - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    - pods
    verbs:
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - clickhouse.altinity.com
    resources:
    - clickhouseinstallations
    verbs:
    - delete
    - get
    - patch
    - update
  - apiGroups:
    - apps
    resourceNames:
    - clickhouse-operator
    resources:
    - deployments
    verbs:
    - get
    - patch
    - update
    - delete
  - apiGroups:
    - apps
    resources:
    - replicasets
    verbs:
    - delete
    - get
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - patch
      - update
      - list
      - watch
  - apiGroups:
    - clickhouse.altinity.com
    resources:
    - clickhouseinstallations
    - clickhouseinstallationtemplates
    - clickhouseoperatorconfigurations
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - clickhouse.altinity.com
    resources:
      - clickhouseinstallations/finalizers
      - clickhouseinstallationtemplates/finalizers
      - clickhouseoperatorconfigurations/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - patch
      - update
      - list
      - watch
---
# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator-kube-system
  labels:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator-kube-system
subjects:
- kind: ServiceAccount
  name: {{ template "ch.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
