# Default values for cloudflare-collection.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Before installing the chart, you must first install cert-manager, and the origin-ca-issuer CustomResourceDefinition resources.
# VERSION="v0.7.0"
# kubectl apply -f https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/${VERSION}/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
originIssuer:
  enabled: false
  issuerName: origin-issuer
  secret: 
    origin_ca_api_key: "v1.0-FFFFFFF-FFFFFFFF"
  certificate:
    enabled: false
    secretName: secret-example
    domains:
      - "example.com"
      - "*.example.com"
    duration: "168h"
# As per the Helm best practices, cloudflareOperator Helm chart doesn’t ship with CRDs.
# kubectl apply -f https://github.com/containeroo/cloudflareOperator/releases/latest/download/crds.yaml
cloudflareOperator:
  enabled: false
  accounts: 
    - zone: "example.com"
      secret: "account-zone-api-key"
  dnsRecords:
    - name: "www.example.com"
      type: CNAME
      content: "example.com"
      proxied: {}
      ttl: {}
      interval: {}
