{{- if .Values.secret }}
{{- $fullName := include "raw.fullname" . -}}
{{- $NS := .Release.Namespace -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "raw.fullname" . }}
type: Opaque
data:
{{- range $path, $bytes := .Values.secret.data }}
  {{ $path }}: '{{ $bytes | b64enc }}'
{{- end }}
{{- range $path, $bytes := .Values.secret.gendata }}
  {{ $path }}: {{ include "raw.password" (dict "secretKey" $path "Ns" $NS "secretName" $fullName) | b64enc | quote }}
{{- end }}
{{- end}}

