{{- if .Values.filebeat.enabled -}}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
spec:
  type: filebeat
  version: {{ .Chart.AppVersion }}
  elasticsearchRef:
    name: {{ .Values.elastic.nameref }}
  kibanaRef:
    name: {{ .Values.kibana.nameref }}
  config:
    filebeat.autodiscover:
      providers:
      - type: kubernetes
        hints.enabled: true
        node: ${NODE_NAME}
        hints.default_config:
          enabled: false
          type: container
          paths:
            - /var/log/containers/*-${data.container.id}.log  # CRI path

    logging:
      level: info
    # output.elasticsearch:
    #   index: "filebeat-rbkmoney-processing-write-alias"
    # Attention! Can't push to multiple indices with current config scheme!
    # https://github.com/elastic/beats/issues/11866
    setup:
      ilm:
        enabled: true
        overwrite: true
        rollover_alias: filebeat-rbkmoney-processing # должно совпадать с полем в files/filebeat-index-template.json
        policy_file: "/mnt/rbkmoney/ilm-policy.json"
        policy_name: "filebeat-rbkmoney-processing-ilm-policy"
      dashboards:
        enabled: false
        index: filebeat-rbkmoney-processing-*
      template:
        enabled: true
        overwrite: true
        json:
          enabled: true
          path: "/mnt/rbkmoney/template.json"
          name: filebeat-rbkmoney-processing
  daemonSet:
    podTemplate:
      spec:
        nodeSelector: {}
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: filebeat-configs
            mountPath: /mnt/rbkmoney/
            readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: filebeat-configs
          configMap:
            name: filebeat-configs
            items:
            - key: index_template_json
              path: template.json
            - key: ilm_policy_json
              path: ilm-policy.json
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
