---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configs
  labels:
    k8s-app: filebeat
data:
  index_template_json: |
    {{- .Files.Get "files/filebeat-index-template.json" | nindent 4 }}
  ilm_policy_json: |
    {
       "policy": {
         "phases": {
           "hot": {
             "min_age": "0ms",
             "actions": {
               "rollover": {
                 "max_age": "{{ .Values.elastic.data.retention.rollover }}h"
               },
               "set_priority": {
                 "priority": 100
               }
             }
           },
           "warm": {
             "min_age": "{{ .Values.elastic.data.retention.warm }}h",
             "actions": {
               "set_priority": {
                 "priority": null
               }
             }
           },
           "delete": {
             "min_age": "{{ .Values.elastic.data.retention.delete }}h",
             "actions": {
               "delete": {
                 "delete_searchable_snapshot": true
               }
             }
           }
         }
       }
    }
