# Default values for origin-issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

issuerName: cloudflare-origin-issuer
secret: 
  origin_ca_api_key: "v1.0-FFFFFFF-FFFFFFFF"
certificate:
  enabled: false
  secretName: secret-example
  domains:
    - "example.com"
    - "*.example.com"
  duration: "168h"