{{- if and .Values.internal_users (eq .Values.nodeGroup "pus") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.clusterName }}-internal-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  internal_users.yml: |
    _meta:
      type: "internalusers"
      config_version: 2

    {{ range .Values.internal_users -}}  
    {{ .name }}:
      hash: {{ .password | bcrypt }}
      reserved: {{ .reserved | default false }}
      {{- if .backend_roles }}
      backend_roles:
        {{- range .backend_roles }}
        - {{ . }}
        {{- end }}
      {{ end }}
    {{ end }}
{{- end -}}
