{{- if .Values.cilium.enabled }}
{{- if not .Values.cilium.policy.enabled }}
{{- range .Values.netPolicies }}
  {{- if or (eq .name "world") (regexMatch "^fqdn-.*" .name) }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-egress
  namespace: {{ $.Values.processingNamespace | default $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium/release: {{ $.Release.Name }}
  egress:
  {{- if eq .name "world" }}
  - toEntities:
      - world
  {{- else if (regexMatch "^fqdn-.*" .name) }}
  - toFQDNs:
    {{- if .matchName }}
    {{- range .matchName }}
    - matchName: "{{ . }}"
    {{- end }}
    {{- end }}
    {{- if .matchPattern }}
    {{- range .matchPattern }}
    - matchPattern: "{{ . }}"
    {{- end }}
    {{- end }}
    toPorts:
    - ports:
      {{- range .filters }}
      - protocol: {{ .type }}
        {{- if .endPort }}
        port: {{ printf "%s-%s" .port .endPort }}
        {{- else}}
        port: {{ .port | quote }}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}