{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium/release: {{ .Release.Name }}
  egress:
  {{- range .Values.netPolicies }}
  - toEndpoints:
    - matchLabels:
        k8s:selector.cilium/release: {{ .name }}
    toPorts:
      - ports:
    {{- range .filters }}
        - protocol: {{ .type }}
          port: {{ .port | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
