{{- if .Values.netpolicy }}
{{- if .Values.netpolicy.enabled }}
{{- $relname := .Release.Name -}}
{{- $relnamespace := .Release.Namespace -}}
{{ range .Values.netPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- if .group }}
  name: {{ $relname }}-{{ .group }}-ingress
  {{- else }}
  name: {{ $relname }}-{{ .name }}-ingress
  {{- end}}
  namespace: {{ $relnamespace }}
spec:
  podSelector:
    matchLabels:
      {{- if .group }}
      selector.cilium/group: {{ .group }}
      {{- else }}
      selector.cilium/release: {{ .name }}
      {{- end }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          selector.cilium/release: {{ $relname }}
    ports:
    {{- range .filters }}
    - protocol: {{ .type }}
      port: {{ .port }}
      {{- if .endPort }}
      endPort: {{ .endPort }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
