apiVersion: v1
kind: Service
metadata:
  name: {{ include "stateless.fullname" . }}
  labels:
{{ include "stateless.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "stateless.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
