apiVersion: v1
kind: Service
metadata:
  name: {{ include "stateless.fullname" . }}
  labels:
{{ include "stateless.labels" . | indent 4 }}
  {{- if or .Values.service.annotations .Values.TopologyAwareRouting.enabled }}
  annotations:
    {{- if .Values.TopologyAwareRouting.enabled }}
    service.kubernetes.io/topology-aware-hints: auto
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "stateless.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
