{{- if .Values.runInClusterScope }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "keycloak-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    {{- if .Values.runInClusterScope }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
    name: {{ include "keycloak-operator.fullname" . }}-sa
roleRef:
  {{- if .Values.runInClusterScope }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "keycloak-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
