{{- if .Values.keycloak.externalDatabase }}
{{- if .Values.keycloak.externalDatabase.enabled }}
# https://github.com/keycloak/keycloak-operator/blob/main/deploy/examples/keycloak/external-db-secret.yaml
# https://github.com/keycloak/keycloak-operator/blob/77d126113104d45e29057f5c9e30c54f1a482763/pkg/model/database_secret.go

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-operator.keycloak.applicationName" . }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "keycloak-operator.keycloak.applicationName" . }}
type: Opaque
data: # all values Base64
  POSTGRES_DATABASE: {{ printf "%s" .Values.keycloak.externalDatabase.database | b64enc }}
  POSTGRES_EXTERNAL_ADDRESS: {{ printf .Values.keycloak.externalDatabase.host | b64enc }}
  POSTGRES_EXTERNAL_PORT: {{ printf "%.0f" .Values.keycloak.externalDatabase.port | b64enc }}
  POSTGRES_USERNAME: {{ printf "%s" .Values.keycloak.externalDatabase.username | b64enc }}
  POSTGRES_PASSWORD: {{ printf "%s" .Values.keycloak.externalDatabase.password | b64enc }}

---
{{- end }}
{{- end }}

{{- if .Values.keycloak.adminCredentials }}
# https://github.com/keycloak/keycloak-operator/blob/77d126113104d45e29057f5c9e30c54f1a482763/pkg/model/keycloak_admin_secret.go

apiVersion: v1
kind: Secret
metadata:
  name: credential-{{ include "keycloak-operator.fullname" . }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "keycloak-operator.keycloak.applicationName" . }}
    keycloak: {{ include "keycloak-operator.fullname" . }}-keycloak
type: Opaque
data: # all values Base64
  ADMIN_USERNAME: {{ printf "%s" .Values.keycloak.adminCredentials.username | b64enc }}
  ADMIN_PASSWORD: {{ printf "%s" .Values.keycloak.adminCredentials.password | b64enc }}

---
{{- end }}
