apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels: {{- include "keycloak-operator.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
