{{- if .Values.cilium }}
{{- if .Values.cilium.policy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium/release: {{ .Release.Name }}
  egress:
  {{- range .Values.netPolicies }}
  - toEndpoints:
    - matchLabels:
        {{- if .group }}
        k8s:selector.cilium/group: {{ .group }}
        {{- else }}
        k8s:selector.cilium/release: {{ .name }}
        {{- end }}
    toPorts:
      - ports:
    {{- range .filters }}
        - protocol: {{ .type }}
          {{- if .endPort }}
          port: {{ printf "%s-%s" .port .endPort }}
          {{- else}}
          port: {{ .port | quote}}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
