apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clickhouse-knp-policy
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: clickhouse-operator
  policyTypes:
    - Egress
  egress:
  - to:
      - ipBlock:
          cidr: {{ .Values.services.kafka.cidr }}
    ports:
    - protocol: TCP
      port: 2181
    - protocol: TCP
      port: 2182