apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: consul-knp-policy
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: consul
  policyTypes:
    - Egress
    - Ingress
  egress:
  - to:
    - podSelector:
        matchLabels:
          selector.cilium/release: machinegun-ha
  - to:
    - podSelector:
        matchLabels:
          selector.cilium/release: consul
  - to:
    - ipBlock:
        cidr: 13.33.243.0/24
  - to:
    - ipBlock:
        cidr: 143.204.215.0/24
  ingress:
  - from:
    - podSelector:
        matchLabels:
          selector.cilium/release: machinegun-ha
  - from: 
    - podSelector:
        matchLabels:
          selector.cilium/release: consul
