apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: fqdn.default
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toFQDNs:
      - matchPattern: "*{{- .Values.services.ingress.rootDomain | default "example.com" -}}"
    toPorts:
      - ports:
         - port: "80"
           protocol: TCP
         - port: "443"
           protocol: TCP