{{- if and .Values.netpolicy .Values.netpolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-init-egress
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: postgres-init
  policyTypes:
  - Egress
  egress:
  {{- if .Values.services.postgres.external }}
  - to:
      {{- range .Values.services.postgres.cidrs }}
    - ipBlock:
        cidr: {{ . }}
      {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.services.postgres.port | default "5432" }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-init-egress
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: kafka-init
  policyTypes:
  - Egress
  egress:
  {{- if .Values.services.kafka.external }}
  - to:
      {{- range .Values.services.kafka.cidrs }}
      - ipBlock:
          cidr: {{ . }}
      {{- end }}
    ports:
    - protocol: TCP
      port: 9092
    - protocol: TCP
      port: 9094
    - protocol: TCP
      port: 9096
    - protocol: TCP
      port: 9098
  {{- end }}
{{- end }}