---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: zone.monitoring
specs:
  - endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: monitoring
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: monitoring
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
  - endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: monitoring
        k8s:app: prometheus
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
  - endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
    ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            k8s:app: prometheus
      toPorts:
      - ports:
        - protocol: TCP
          port: "8080"
        - protocol: TCP
          port: "8023"
        - protocol: TCP
          port: "8022"
        rules:
          http:
          - method: "GET"
            path: "/metrics"
          - method: "GET"
            path: "/actuator/prometheus"
      