{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "keycloak-postgres"
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium/release: keycloak
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:selector.cilium/release: postgres
      toPorts:
      - ports:
        - protocol: TCP
          port: "5432"
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium/release: postgres
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:selector.cilium/release: keycloak
      toPorts:
      - ports:
        - protocol: TCP
          port: "5432"
{{- end }}
{{- end }}