{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: keycloak-kube-api-egress.default
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      name: keycloak
  egress:
  - toEntities:
    - kube-apiserver
{{- end }}
{{- end }}
