{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "default.host"
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium/release: machinegun-ha
    egress:
    - toEntities:
        - host
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium/release: machinegun-ha
    ingress:
    - fromEntities:
      - host
{{- end }}
{{- end }}