{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
{{- if .Values.extraWorldAccess.enabled }}
{{ range .Values.extraWorldAccess.policy }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: extra-{{ .name }}.default
  namespace: {{ $.Values.processingNamespace | default $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium/release: {{ .podLabel }}
  egress:
    - toEntities:
        - world
{{- end }}
{{- end }}
{{- end }}
{{- end }}