{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
{{- if .Values.extraWorldAccess.enabled }}
{{ range .Values.extraWorldAccess.policy }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: extra-{{ .name }}.default
  namespace: {{ .namespace | default $.Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
    {{- if or (eq .podLabel "adapters") (eq .podLabel "adapters-payout") }}
      k8s:selector.cilium/group: {{ .podLabel }}
    {{- else }}
      k8s:selector.cilium/release: {{ .podLabel }}
    {{- end }}
  egress:
    - toEntities:
        - world
{{- end }}
{{- end }}
{{- end }}
{{- end }}
