{{- if .Values.extraPolicy }}
{{- range .Values.extraPolicy.policy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-egress-policy
  namespace: {{ .namespace | default $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- if .podLabel }}
      selector.cilium/release: {{ .podLabel }}
      {{- else }}
      {{ .customLabel }}
      {{- end }}
  policyTypes:
    - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- if .to.targetLabel }}
          selector.cilium/release: {{ .to.targetLabel }}
          {{- else }}
          {{ .to.customTargetLabel }}
          {{- end }}
      {{- if .to.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .to.namespace | default $.Release.Namespace }}
      {{- end }}
    {{- if .to.ports }}
    ports:
    {{- range .to.ports }}
    - protocol: {{ .type }}
      port: {{ .port }}
      {{- if .endPort }}
      endPort: {{ .endPort }}      
      {{- end }}
    {{- end }}
    {{- end  }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-ingress-policy
  namespace: {{ .to.namespace | default $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- if .to.targetLabel }}
      selector.cilium/release: {{ .to.targetLabel }}
      {{- else }}
      {{ .to.customTargetLabel }}
      {{- end }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- if .podLabel }}
          selector.cilium/release: {{ .podLabel }}
          {{- else }}
          {{ .customLabel }}
          {{- end }}
      {{- if .to.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .namespace | default $.Release.Namespace }}
      {{- end }}
    {{- if .to.ports }}
    ports:
    {{- range .to.ports }}
    - protocol: {{ .type }}
      port: {{ .port }}
      {{- if .endPort }}
      endPort: {{ .endPort }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}