apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fleet-policy
  namespace: {{ .Values.monitoringNamespace | default "monitoring" }}
spec:
  podSelector:
    matchLabels:
      app: fleet
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
          cidr: 169.254.169.254/32
    ports:
    - protocol: TCP
      port: 80
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: fleet-redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: fleet-db
    ports:
    - protocol: TCP
      port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fleet-db-policy
  namespace: {{ .Values.monitoringNamespace | default "monitoring" }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: fleet-db
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: fleet
    ports:
    - protocol: TCP
      port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fleet-redis-policy
  namespace: {{ .Values.monitoringNamespace | default "monitoring" }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: fleet-redis
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: fleet
    ports:
    - protocol: TCP
      port: 6379