{{- if .Values.services.holmesFullAccess }}
{{- if .Values.services.holmesFullAccess.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: holmes-full-access-policy
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: holmes
  policyTypes:
    - Egress
  egress:
  - {}
{{- end }}
{{- end }}