---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controller-to-default-ingress
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controller-to-monitoring-ingress
  namespace: monitoring
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress