apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controller-to-default-ingress
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress