{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-kafka-brokers"
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium/release: kafka
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:selector.cilium/release: kafka
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:selector.cilium/release: kafka
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
{{- end }}
{{- end }}