apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-knp-policy
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: keycloak
  policyTypes:
    - Egress
    - Ingress
  egress:
  - to:
    - podSelector:
        matchLabels:
          selector.cilium/release: keycloak
  - to:
  {{- if .Values.services.postgres.external }}
      - ipBlock:
          cidr: {{ .Values.services.postgres.cidr }}
  {{- else }}
    - podSelector:
        matchLabels:
          selector.cilium/release: postgres
  {{- end }}
    ports:
      - protocol: TCP
        port: {{ .Values.services.postgres.port | default "5432" }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          selector.cilium/release: keycloak