{{- if .Values.netpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: {{ .Release.Name }}
  policyTypes:
  - Egress
  egress:
  {{- range .Values.netPolicies }}
  - to:
    - podSelector:
        matchLabels:
          selector.cilium/release: {{ .name }}
    ports:
    {{- range .filters }}
    - protocol: {{ .type }}
      port: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }}