{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statefull.fullname" . }}
type: Opaque
data:
{{- range $path, $bytes := .Values.secret.data }}
  {{ $path }}: '{{ $bytes | b64enc }}'
{{- end }}
{{- end}}

