{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "statefull.serviceAccountName" . }}
  labels:
{{ include "statefull.labels" . | indent 4 }}
{{- end -}}
