{{- if .Values.service.headless }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefull.fullname" . }}-headless
  labels:
{{ include "statefull.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  publishNotReadyAddresses: True
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "statefull.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
