{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ch.serviceAccountName" . }}
  labels:
    clickhouse.altinity.com/chop: 0.18.0
{{ include "ch.labels" . | indent 4 }}
{{- end -}}
