kind: Service
apiVersion: v1
metadata:
  name: clickhouse-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    clickhouse.altinity.com/chop: {{ .Chart.AppVersion | quote }}
    app: clickhouse-operator
spec:
  ports:
    - port: 8888
      name: clickhouse-operator-metrics
  selector:
    app: clickhouse-operator
